language: c

sudo: false

env:
  global:
   - RACKET_DIR=~/racket
  matrix:
   - RACKET_VERSION=6.10
   - RACKET_VERSION=6.11
   - RACKET_VERSION=6.12
   - RACKET_VERSION=HEAD

matrix:
  allow_failures:
   - env: RACKET_VERSION=HEAD
  fast_finish: true

before_install:
 - cd ..
 - git clone https://github.com/greghendershott/travis-racket.git
 - cat travis-racket/install-racket.sh | bash # pipe to bash not sh!
 - export PATH="${RACKET_DIR}/bin:${PATH}"

install:

before_script:

script:
 - cd typed-module-lang
 - raco pkg install --name typed-module-lang-lib --deps search-auto --link lib
 - raco pkg install --name typed-module-lang-test --deps search-auto --link test
 - raco pkg install --name typed-module-lang-doc --deps search-auto --link doc
 - raco test -p typed-module-lang-lib typed-module-lang-test

after_script:
